### ISSUE TITLE
Social Media Handle Page: No sections for youtube, spotify, instagram, apple music, google podcast thing

### ISSUE THREAD

**Issue by praveenpkg8** [praveenpkg8/dattebayo#10]
No sections for youtube, spotify, instagram, apple music, google podcast thing

_Originally posted by @praveenpkg8 in https://github.com/praveenpkg8/dattebayo/issues/5#issuecomment-1312661388_

**Comment by dhanasekar-dsds** [comment]
![p2](https://user-images.githubusercontent.com/59327671/201698723-aff8120c-4741-49ee-aac3-d075339e9e87.jpg)
![p3](https://user-images.githubusercontent.com/59327671/201698764-522434db-4738-41fb-b64e-155068eedc8d.jpg)
![p4](https://user-images.githubusercontent.com/59327671/201698774-e9f65bbd-6262-4fe0-876b-000345c36a50.jpg)
![p5](https://user-images.githubusercontent.com/59327671/201698790-3d07e786-b5d2-4285-ae0b-73d39e11ba13.jpg)
![p6](https://user-images.githubusercontent.com/59327671/201698814-6b9dd883-37b4-42ff-b6c3-eb55d34f1e1e.jpg)
![p7](https://user-images.githubusercontent.com/59327671/201698831-035620b6-23d1-4fd0-bdab-6e27ec88a0fe.jpg)
![p1](https://user-images.githubusercontent.com/59327671/201698852-b8a7b20d-3688-47a3-a611-9730c3a7bf88.jpg)
